# Generated by Django 2.1.1 on 2018-10-06 05:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeanUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('profile_picture', models.ImageField(blank=True, default='default/avatar-default.jpg', max_length=255, null=True, upload_to=core.models.photo_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=80, null=True)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lean Users',
                'db_table': 'users',
            },
        ),
    ]
